spring:
  application:
    name: api

  server:
    port: 8080

  datasource:
    primary:  # MySQL ?????
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/REALWORLD
      username: root
      password: 1234

    secondary:  # H2 ?????
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:test
      username: sa
      password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  security:
    user:
      name: admin
      password: admin

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: realWorldByGiro123456789qwerasdfrealWorldByGiro123456789qwerasdf
  expiration: 86400000
